---
apiVersion: v1
kind: Service
metadata:
  name: sweety-svc
  labels:
    app: sweety
spec:
   - type: LoadBalancer
     selector: 
       app: sweety
     ports:
       - name: sweety-svc
         port: 8080
         protocol: TCP
         targetPort: 8080                          